# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06346c3a5e05330aab64c1538cea233778696598797e0e033c6085e9a6bb850a74a634ffcc5a3ef3b16168873e456681f8452543df3139f377ddbcb44272f4b8

test:
  secret_key_base: ccb8d2b4661fc11ecab006ee15f4f0775ad72a09286e794758e34ba2ae04c72a3b352cbe7b21af205516f015d53ab653525c52ca5b6dec2dbf6fac8ef945893b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
